Initial commit of comment-visualizer-vk
i-pankrat/comment-visualizer-vk pull request #1
Opened 2022-12-08 16:54 UTC by i-pankrat

Add basic functionality for generating images from the comments of a post on VKontakte.
Author: Ilya Pankratov

2022-12-08 17:01 UTC, i-pankrat commented
Reviewer: @SpirinEgor

2022-12-09 16:36 UTC, SpirinEgor requested changes
A nice complex solution, but I see some problems with interaction between objects (and their absence). You should separate logic from generating images and displaying them.

2022-12-09 16:36 UTC, SpirinEgor commented on src/CommentVisualizerLib.py
> +kw_getter = KeyWordsGetter()
I don't like that you define these in a global area. Because this will cause re-init on each import. It is better to wrap logic inside a class.

2022-12-09 16:36 UTC, SpirinEgor commented on src/CommentVisualizerLib.py
> +    global vk, neural_networks, kw_getter
Using `global` in almost all cases is a smell of bad code 🙃 Consider to use classes for this logic.

2022-12-09 16:36 UTC, SpirinEgor commented on src/CommentVisualizerLib.py
> +    neural_networks.convert_image(en_text, device, file_name, steps, height, width)
And no return of that image? Kind of unobvious solution

2022-12-09 16:36 UTC, SpirinEgor commented on src/config.py
> +vk_api_version = "5.131"
Use UPPER_CASE for such constants. `SECRET_KEY` for example.
And add comments or docs about this secret key. Is it from VK or from HF? How to get it?

2022-12-09 16:36 UTC, SpirinEgor commented on src/models.py
> +class NeuralNetworkmanager:
I guess you have a typo here: `NeuralNetworkManager`

2022-12-09 16:36 UTC, SpirinEgor commented on src/models.py
> +            self.__initialize_image_converter__(device)
Why don't you just initialize the model in the constructor of this class?

2022-12-09 16:36 UTC, SpirinEgor commented on src/streamlit_app.py
> +from os.path import exists, join
Wrap streamlit app in the main method, this will better organize your code and will help you with possible extensions in the future.

2022-12-09 16:36 UTC, SpirinEgor commented on src/config.py
> +vk_api_version = "5.131"
Also, the best way to handle secret keys is to read them from environment variables. This will avoid accidentally pushing sensitive information to git.

2022-12-09 16:36 UTC, SpirinEgor commented on src/utilsTests.py
> +import unittest
From the repo organization side, it is better to create a `tests` folder next to the `src` folder. In this way, you wouldn't mix the main functionality with additional tests.

2022-12-13 19:21 UTC, i-pankrat commented on src/utilsTests.py
> +import unittest
Done [acc733d](https://github.com/i-pankrat/comment-visualizer-vk/pull/1/commits/acc733d4868bd667d362f39d8fd2a2156677e40d)

2022-12-13 19:22 UTC, i-pankrat commented on src/streamlit_app.py
> +from os.path import exists, join
Fix [e5c882c](https://github.com/i-pankrat/comment-visualizer-vk/pull/1/commits/e5c882c03d729c26af24027b24a9833ef5a7198a)

2022-12-13 19:23 UTC, i-pankrat commented on src/models.py
> +class NeuralNetworkmanager:
You're right! Thank you!

2022-12-13 19:25 UTC, i-pankrat commented on src/config.py
> +vk_api_version = "5.131"
Implement in [a9f2185](https://github.com/i-pankrat/comment-visualizer-vk/pull/1/commits/a9f218501733d3ffb72a2ccb27d6330bc1a32791) and [0bff9b6](https://github.com/i-pankrat/comment-visualizer-vk/pull/1/commits/0bff9b65d22825164fcb0396b779a7382bde1d2a)

2022-12-13 19:26 UTC, i-pankrat commented on src/models.py
> +            self.__initialize_image_converter__(device)
Fix that in [d46fa0c](https://github.com/i-pankrat/comment-visualizer-vk/pull/1/commits/d46fa0c4c7c3557366cfec2de8e70eca6b4dd37f)

2022-12-13 19:27 UTC, i-pankrat commented on src/CommentVisualizerLib.py
> +    neural_networks.convert_image(en_text, device, file_name, steps, height, width)
Agree, fixed in [d46fa0c](https://github.com/i-pankrat/comment-visualizer-vk/pull/1/commits/d46fa0c4c7c3557366cfec2de8e70eca6b4dd37f)

2022-12-13 19:27 UTC, i-pankrat commented on src/CommentVisualizerLib.py
> +    global vk, neural_networks, kw_getter
Fixed in [d46fa0c](https://github.com/i-pankrat/comment-visualizer-vk/pull/1/commits/d46fa0c4c7c3557366cfec2de8e70eca6b4dd37f)

2022-12-13 19:30 UTC, i-pankrat commented on src/CommentVisualizerLib.py
> +kw_getter = KeyWordsGetter()
Fixed in [d46fa0c](https://github.com/i-pankrat/comment-visualizer-vk/pull/1/commits/d46fa0c4c7c3557366cfec2de8e70eca6b4dd37f)
I store a copy of CommentVisualizer at session_state to avoid re-init on updating page

2022-12-14 15:31 UTC, SpirinEgor reviewed
Your app is great, I enjoy your solution.
Fix CI and I will approve this PR.

2022-12-15 10:58 UTC, i-pankrat commented on .github/workflows/CI.yml
> +    branches: [ "main" ]
Fixed in [9b0d3b9](https://github.com/i-pankrat/comment-visualizer-vk/pull/1/commits/9b0d3b9fc1f85d4065fada1c9426c9edb630c2ff)

2022-12-15 10:59 UTC, i-pankrat commented on .github/workflows/CI.yml
> +      - uses: psf/black@stable
Remove black linter to avoid conflicts [b1c41da](https://github.com/i-pankrat/comment-visualizer-vk/pull/1/commits/b1c41da9bb1e2ff9a3b67f10919911d17b79dd63)

2022-12-20 11:09 UTC, SpirinEgor approved these changes
Nice work 👍

2023-01-08 08:11 UTC, merged